version: '3'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8555:8444" 
    restart: unless-stopped
    networks: 
      - backend

networks:
  backend:    
    driver: bridge   
